### ISSUE TITLE
Nutshell executable cannout be found

### ISSUE THREAD

**Issue by novotny1akub** [schochastics/quarto-nutshell#1]
This looks like an awesome extension, but to me, it does not seem to be working. I tried to install nutshell using `quarto install extension schochastics/quarto-nutshell`, and all seemed to be going well. After that, I added the filters to the YAML header, and tried to render my document. For some reason, it gives me the following error `Error running filter nutshell: Could not find executable nutshell`. My Quarto version is 1.2.69 and I am on Windows.

How can I check if the extension was actually installed?

**Comment by novotny1akub** [comment]
No, I'm afraid I didn't. Sorry about that - this is the first time using a Quarto extension for me.

**Comment by schochastics** [comment]
No worries. Did the same mistake in the beginning too. It is never explicitly mentioned anywhere
