### ISSUE TITLE
Work with cross-references?

### ISSUE THREAD

**Issue by tobydriscoll** [schochastics/quarto-nutshell#2]
I'd be over the moon with this extension if it could handle cross-references. For example,

```{markdown}
$$
e^{ix} = \cos(x) + i \sin(x)
$$ {#eq-euler-identity}

Some think that :@eq-euler-identity is one of the most beautiful equations in all of mathematics.
 ```

This would give "Equation 1.1" as a nutshell-style link instead of the standard text link we get from `@eq-euler-identity`.

I thought I might get by with `[:the Euler equation](#eq-euler-identity)`, since the standard cross-reference link target is actually to a section hashtag in the final page, but that doesn't work, either. 

What are the prospects of making this happen?

**Comment by schochastics** [comment]
I love this use case but I am afraid that this might need to be implemented in the actual [nutshell library](https://ncase.me/nutshell/). However, I found a way to get it kind of done

```md
---
title: "Euler equation"
author: ""
format: html
filters:
    - nutshell
---
    
$$
e^{ix} = \cos(x) + i \sin(x)
$${#eq-black-scholes}

The [:Euler equation](#eq-black-scholes_nut) is pretty nice.

## :x eq-black-scholes_nut

$$
e^{ix} = \cos(x) + i \sin(x)
$$
```

This is certainly not 100% satisfactory, but I am not sure if one can get any closer without implementing this in the original library

**Comment by schochastics** [comment]
Ok so 
`The [:@eq-black-scholes](#eq-black-scholes_nut) is pretty nice.` actually works, but you need to press on the colon to get the expanded version. That is also a rather suboptimal solution

**Comment by tobydriscoll** [comment]
Interesting workaround! I wouldn't manually make two copies of every equation, figure, etc., but I suppose it could be done via scripts before rendering. 

The nutshell version of the equation is typeset differently, though, and not well--the "i sin(x)" is run together, for example, in my browser.

**Comment by schochastics** [comment]
Yes its not really a good workaround, but since this extension only wraps around the nutshell javascript library, there is unfortunately not much else one can do

**Comment by tobydriscoll** [comment]
Thanks for having a go at it anyway!
