### ISSUE TITLE
Nutshell after every heading

### ISSUE THREAD

**Issue by xinzhuohkust** [schochastics/quarto-nutshell#4]
Hi, thanks for your excellent work! I got a question.
This plugin creates a nutshell after every heading. Is there a way to disable this feature?
![image](https://github.com/schochastics/quarto-nutshell/assets/99251348/d3630f7f-5b2a-44e1-bff1-f26e319a426e)

Best,
Hsincho

**Comment by schochastics** [comment]
You probably need to edit some css. The image shows the definition of `.nutshell-heading-embeded`
![Screenshot from 2023-07-10 08-51-10](https://github.com/schochastics/quarto-nutshell/assets/17147355/c5d78dc3-e73e-454c-b9d6-95a532cadc36)

Add a custom `style.css` to you document with
```css
.nutshell-heading-embeded{
   display: none!important;
}
```

**Comment by ute** [comment]
did not work for me (quarto 1.4), but the newer versions of nutshell.js have the possibility to switch off the nut by javascript, [see here](https://github.com/ncase/nutshell?tab=readme-ov-file#configuring-nutshell)  :-)

**Comment by schochastics** [comment]
Thanks for flagging this! I will update the extension accordingly

**Comment by schochastics** [comment]
@xinzhuohkust  @ute should be fixed now. There is a [new file](https://github.com/schochastics/quarto-nutshell/blob/main/_extensions/nutshell/nutshell_options.js) where one can turn the shell on and off. It is off by default.

**Comment by xinzhuohkust** [comment]
Thank you for your excellent work.
